version: "3.9"

services:
  backend:
    container_name: mentia_backend
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    # Si us√°s archivo .env:
    # env_file:
    #   - .env
    restart: unless-stopped
